import { ProjectConfig, TemplateId } from "../types";

// ─────────────────────────────────────────────
// Template Engine — in-memory boilerplate strings
// ─────────────────────────────────────────────

export class TemplateEngine {
  render(templateKey: string, config: ProjectConfig): string {
    const fn = BOILERPLATE[templateKey];
    if (!fn) return `// TODO: ${templateKey}\n`;
    return fn(config);
  }

  renderByPath(filePath: string, config: ProjectConfig): string {
    const key = pathToTemplateKey(filePath);
    return this.render(key, config);
  }
}

/** Map common file paths to a template key */
function pathToTemplateKey(filePath: string): string {
  if (filePath.endsWith("app.ts")) return "app.ts";
  if (filePath.endsWith("server.ts")) return "server.ts";
  if (
    filePath.endsWith(".env.example") ||
    filePath.endsWith(".env.local.example")
  )
    return ".env.example";
  if (filePath.endsWith("tsconfig.json")) return "tsconfig.json";
  if (filePath.endsWith("package.json")) return "package.json";
  if (filePath.endsWith("README.md")) return "README.md";
  if (filePath.endsWith("Dockerfile")) return "Dockerfile";
  if (filePath.endsWith("docker-compose.yml")) return "docker-compose.yml";
  if (filePath.includes(".github/workflows/ci.yml")) return "github-ci";
  if (filePath.endsWith("jest.config.ts")) return "jest-config";
  if (filePath.endsWith("auth.middleware.ts")) return "auth-middleware";
  if (filePath.endsWith("auth.service.ts")) return "auth-service";
  if (filePath.endsWith("auth.controller.ts")) return "auth-controller";
  if (filePath.endsWith("auth.routes.ts")) return "auth-routes";
  if (filePath.endsWith("next.config.mjs")) return "next.config.mjs";
  if (filePath.endsWith("tailwind.config.ts")) return "tailwind.config.ts";
  return "generic";
}

// ─── Boilerplate renderers ────────────────────────────────────────────────────

type Renderer = (config: ProjectConfig) => string;

const BOILERPLATE: Record<string, Renderer> = {
  "app.ts": (c) => `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';

const app = express();

app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(morgan('dev'));

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', project: '${c.projectName}' });
});

// TODO: Import and register your routes here
// import { authRouter } from './routes/auth.routes';
// app.use('/api/auth', authRouter);

export default app;
`,

  "server.ts": (c) => `import 'dotenv/config';
import app from './app';

const PORT = Number(process.env.PORT) || 3000;

app.listen(PORT, () => {
  console.log(\`🚀  ${c.projectName} running on http://localhost:\${PORT}\`);
});
`,

  ".env.example": (_c) => `# Application
NODE_ENV=development
PORT=3000

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/dbname

`,

  "tsconfig.json": (_c) => `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`,

  "package.json": (c) => `{
  "name": "${c.projectName}",
  "version": "0.1.0",
  "description": "${c.description ?? ""}",
  "main": "dist/server.js",
  "scripts": {
    "dev": "ts-node-dev --respawn src/server.ts",
    "build": "tsc",
    "start": "node dist/server.js",
    "lint": "eslint src/**/*.ts",
    "test": "jest"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0"
  },
  "devDependencies": {
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.21",
    "@types/morgan": "^1.9.9",
    "@types/node": "^20.14.0",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.4.5"
  }
}
`,

  "README.md": (c) => `# ${c.projectName}

> Generated by [ArchAI](https://github.com/your-org/arch-ai) — Template: \`${c.template}\`

## Getting Started

\`\`\`bash
# Install dependencies
${c.packageManager} install

# Copy environment variables
cp .env.example .env

# Start development server
${c.packageManager} run dev
\`\`\`

## Scripts

| Script | Description |
|--------|-------------|
| \`dev\` | Start dev server with hot reload |
| \`build\` | Compile TypeScript |
| \`start\` | Run production build |
| \`test\` | Run test suite |

## Features

${(c.features ?? []).map((f) => `- ${f}`).join("\n") || "- None selected"}

---
_Scaffolded with ❤️  by ArchAI_
`,

  "auth-middleware": (
    _c,
  ) => `import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

export interface AuthRequest extends Request {
  userId?: string;
}

export function authMiddleware(req: AuthRequest, res: Response, next: NextFunction): void {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) {
    res.status(401).json({ message: 'No token provided' });
    return;
  }
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as { userId: string };
    req.userId = decoded.userId;
    next();
  } catch {
    res.status(401).json({ message: 'Invalid token' });
  }
}
`,

  "auth-service": (_c) => `import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

export class AuthService {
  async hashPassword(password: string): Promise<string> {
    return bcrypt.hash(password, 12);
  }

  async comparePassword(password: string, hash: string): Promise<boolean> {
    return bcrypt.compare(password, hash);
  }

  generateToken(userId: string): string {
    return jwt.sign({ userId }, process.env.JWT_SECRET!, {
      expiresIn: process.env.JWT_EXPIRES_IN ?? '7d',
    });
  }

  verifyToken(token: string): { userId: string } {
    return jwt.verify(token, process.env.JWT_SECRET!) as { userId: string };
  }
}

export const authService = new AuthService();
`,

  "auth-controller": (_c) => `import { Request, Response } from 'express';
import { authService } from '../services/auth.service';

export class AuthController {
  async register(req: Request, res: Response): Promise<void> {
    try {
      const { email, password } = req.body;
      // TODO: Check if user exists, save to DB
      const hashed = await authService.hashPassword(password);
      const token = authService.generateToken('placeholder-user-id');
      res.status(201).json({ token });
    } catch (err) {
      res.status(500).json({ message: 'Registration failed' });
    }
  }

  async login(req: Request, res: Response): Promise<void> {
    try {
      const { email, password } = req.body;
      // TODO: Fetch user from DB, verify password
      const token = authService.generateToken('placeholder-user-id');
      res.json({ token });
    } catch (err) {
      res.status(401).json({ message: 'Invalid credentials' });
    }
  }
}

export const authController = new AuthController();
`,

  "auth-routes": (_c) => `import { Router } from 'express';
import { authController } from '../controllers/auth.controller';

const router = Router();

router.post('/register', (req, res) => authController.register(req, res));
router.post('/login', (req, res) => authController.login(req, res));

export { router as authRouter };
`,

  Dockerfile: (c) => `# ─── Build stage ───────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ─── Production stage ──────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]
`,

  "docker-compose.yml": (c) => `version: '3.9'
services:
  app:
    build: .
    ports:
      - "\${PORT:-3000}:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${c.projectName.replace(/-/g, "_")}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
`,

  "github-ci": (_c) => `name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
`,

  "jest-config": (_c) => `import type { Config } from 'jest';

const config: Config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/*.test.ts'],
  collectCoverageFrom: ['src/**/*.ts', '!src/**/*.d.ts'],
};

export default config;
`,

  "next.config.mjs": (_c) => `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    serverActions: { allowedOrigins: ['*'] },
  },
};

export default nextConfig;
`,

  "tailwind.config.ts": (_c) => `import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,

  generic: (_c) => `// TODO: Implement this module\n`,
};

export const templateEngine = new TemplateEngine();
